if (WITH_GHOSTRIDER)
    add_definitions(/DXMRIG_ALGO_GHOSTRIDER)
    add_subdirectory(src/crypto/ghostrider)
    set(GHOSTRIDER_LIBRARY ghostrider)
else()
    remove_definitions(/DXMRIG_ALGO_GHOSTRIDER)
    set(GHOSTRIDER_LIBRARY "")
    # When ghostrider is disabled, we still need sph_sha2 for other algorithms (e.g. RX_SCASH)
    list(APPEND SOURCES_CRYPTO src/crypto/common/sphlib/sph_sha2.c)
endif()
